### ISSUE TITLE
Use cases ?

### ISSUE THREAD

**Issue by bepolymathe** [macmarrum/freeplane-ScriptExecutionOnMindmapOpen#1]
Hi @macmarrum 

I just spotted this addon. Could you illustrate how you use it? For what purpose I mean...

**Comment by macmarrum** [comment]
You can execute any Groovy script automatically on opening a mindmap.

This could be a simple case of adding a node with a date and time, or a more complicated case of running a NodeChangeListener.

Here's an example: [ScriptExecutionOnMindmapOpen-example.mm.zip](https://github.com/freeplane/freeplane/files/9912408/ScriptExecutionOnMindmapOpen-example.mm.zip)

**Comment by macmarrum** [comment]
See also https://github.com/freeplane/freeplane/discussions/676

**Comment by bepolymathe** [comment]
Thank you 👍🏼 for your answers. Very helpful. I need to think about how I can integrate it into my journaling workflow
